<a href="https://colab.research.google.com/github/Ellen-Git/Machine-Learning/blob/Preprocessing-Data-with-ScikitLearn/Number_of_kids_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0.1    Importing necessary libraries

In [4]:
import numpy as np
import pandas as pd

0.2 Reading the data

In [5]:
data = pd.read_csv("/content/sample_data/data.csv")

0.3 Describing the data

In [6]:
data.head()

Number of Kids  Working Experience(years)  Age  Salary Blood Types
0               3                       15.0   45  250000           A
1               1                        5.0   30  200000           B
2               2                       10.0   38  150000          AB
3               1                        NaN   36  180000           O

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Number of Kids             4 non-null      int64  
 1   Working Experience(years)  3 non-null      float64
 2   Age                        4 non-null      int64  
 3   Salary                     4 non-null      int64  
 4   Blood Types                4 non-null      object 
dtypes: float64(1), int64(3), object(1)
memory usage: 288.0+ bytes


0.4 Filling missing data with median

In [8]:
data["Working Experience(years)"].fillna(data["Working Experience(years)"].median(),inplace=True)

In [9]:
data.head()

Number of Kids  Working Experience(years)  Age  Salary Blood Types
0               3                       15.0   45  250000           A
1               1                        5.0   30  200000           B
2               2                       10.0   38  150000          AB
3               1                       10.0   36  180000           O

In [10]:
data["Working Experience(years)"]=data["Working Experience(years)"].astype(int)

In [11]:
data.head()

Number of Kids  Working Experience(years)  Age  Salary Blood Types
0               3                         15   45  250000           A
1               1                          5   30  200000           B
2               2                         10   38  150000          AB
3               1                         10   36  180000           O

0.5 Finding Correclation between Number of Kids and Age, Number of Kids and Working Experience

In [12]:
data["Number of Kids"].corr(data["Age"])

0.9147673836616229

In [13]:
data["Working Experience(years)"].corr(data["Number of Kids"])

0.8528028654224419

is more related to Number of Kids -  correlation


0.6 One Hot Vectors

In [14]:
blood_types_encoded,categories=data["Blood Types"].factorize()
blood_types_encoded

array([0, 1, 2, 3])

array([0, 1, 2, 3], dtype=int64)

In [15]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
blood_type_cat_1hot = encoder.fit_transform(blood_types_encoded.reshape(-1,1))
blood_type_cat_1hot

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array(



 )

In [16]:
data.head()

Number of Kids  Working Experience(years)  Age  Salary Blood Types
0               3                         15   45  250000           A
1               1                          5   30  200000           B
2               2                         10   38  150000          AB
3               1                         10   36  180000           O

In [17]:
one_hot=pd.get_dummies(data,columns=["Blood Types"],drop_first=False,prefix='',prefix_sep='')
one_hot

Number of Kids  Working Experience(years)  Age  Salary  A  AB  B  O
0               3                         15   45  250000  1   0  0  0
1               1                          5   30  200000  0   0  1  0
2               2                         10   38  150000  0   1  0  0
3               1                         10   36  180000  0   0  0  1

In [18]:
data=data.drop("Blood Types",axis=1)
data

Number of Kids  Working Experience(years)  Age  Salary
0               3                         15   45  250000
1               1                          5   30  200000
2               2                         10   38  150000
3               1                         10   36  180000

In [19]:
data=data.join(one_hot["A"])
data=data.join(one_hot["B"])
data=data.join(one_hot["AB"])
data=data.join(one_hot["O"])

In [20]:
data

Number of Kids  Working Experience(years)  Age  Salary  A  B  AB  O
0               3                         15   45  250000  1  0   0  0
1               1                          5   30  200000  0  1   0  0
2               2                         10   38  150000  0  0   1  0
3               1                         10   36  180000  0  0   0  1

        0.7    Scaling the data

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
data_scaled = pd.DataFrame(scaler.fit_transform(data),columns=
          ["Number of Kids","Working Experience(years)","Age",
           "Salary","Blood Type A","Blood Type B","Blood Type AB",
           "Blood Type O"])

In [23]:
data_scaled

Number of Kids  Working Experience(years)  ...  Blood Type AB  Blood Type O
0        1.507557                   1.414214  ...      -0.577350     -0.577350
1       -0.904534                  -1.414214  ...      -0.577350     -0.577350
2        0.301511                   0.000000  ...       1.732051     -0.577350
3       -0.904534                   0.000000  ...      -0.577350      1.732051

[4 rows x 8 columns]

In [24]:
data_scaled.round(decimals=2)

Number of Kids  Working Experience(years)  ...  Blood Type AB  Blood Type O
0            1.51                       1.41  ...          -0.58         -0.58
1           -0.90                      -1.41  ...          -0.58         -0.58
2            0.30                       0.00  ...           1.73         -0.58
3           -0.90                       0.00  ...          -0.58          1.73

[4 rows x 8 columns]